server:
  port: 8082

spring:
  datasource:
    url: ${env.MYSQL_DATABASE}
    username: ${env.MYSQL_USER}
    password: ${env.MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql